# Generated by Django 4.2.6 on 2023-10-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='features',
            field=models.ManyToManyField(to='main_app.features'),
        ),
    ]
